In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
import chromedriver_autoinstaller
import time

In [ ]:
#INSTALL BROWSER SUCH CHROME OR EDGE
chromedriver_autoinstaller.install()

#USE THE INSTALLED BROWSER FOR SELENIUM
browser = webdriver.Chrome()

In [11]:
data = []

for index in range (1,36):
    browser.get(f'https://www.carsome.id/beli-mobil-bekas?pageNo={index}')
    time.sleep(10)
    soup = BeautifulSoup(browser.page_source, 'lxml')
    rows = soup.find_all('div', class_='list-card__item')
    
    for row in rows:
        merk_element = row.find(class_='mod-card__title')
        merk = merk_element.text.replace("\n", "").strip() if merk_element is not None and merk_element.text.strip() != "" else None
        price_total_element = row.find(class_='mod-card__price__total')
        price_total = price_total_element.text.replace("\n", "").strip() if price_total_element is not None and price_total_element.text.strip() != "" else None
        price_cash_element = row.find(class_='mod-card__price-cash')
        price_cash = price_cash_element.text.replace("\n", "").strip() if price_cash_element is not None and price_cash_element.text.strip() != "" else None
        price_month_element = row.find(class_='mod-tooltipMonthPay')
        price_month = price_month_element.text.replace("\n", "").strip() if price_month_element is not None and price_month_element.text.strip() != "" else None
        keterangan_element = row.find(class_='mod-card__car-other')
        keterangan = keterangan_element.text.replace("\n", "").strip() if keterangan_element is not None and keterangan_element.text.strip() != "" else None
    
        dt = {
            'merk': merk,
            'price_total': price_total,
            'price_cash': price_cash,
            'price_month': price_month,
            'keterangan' : keterangan
            }
        
        data.append(dt)

In [12]:
df = pd.DataFrame(data)

In [13]:
df

,merk,price_total,price_cash,price_month,keterangan
0,2019 Mercedes-Benz C ...,Rp 760.000.000,Rp 780.000.000 (Cash),"Rp 15,48 jt/bln",28.856 km Automatic Tangerang Selatan
1,2016 Mitsubishi PAJERO SP...,Rp 384.000.000,Rp 394.000.000 (Cash),"Rp 7,82 jt/bln",77.584 km Automatic Surabaya
2,2018 Mazda CX-9 ...,Rp 580.000.000,Rp 595.000.000 (Cash),"Rp 11,82 jt/bln",53.282 km Automatic Jakarta Utara
3,2020 BMW X1 SDRIVE...,Rp 653.000.000,Rp 670.000.000 (Cash),"Rp 13,30 jt/bln",35.681 km Automatic Jakarta Barat
4,2018 Mercedes-Benz GLA ...,Rp 570.000.000,Rp 585.000.000 (Cash),"Rp 11,61 jt/bln",33.013 km Automatic Bekasi
...,...,...,...,...,...
695,2018 Suzuki IGNIS ...,Rp 129.000.000,Rp 133.000.000 (Cash),"Rp 2,63 jt/bln",44.363 km Automatic Jakarta Pusat
696,2016 Honda BRIO RS...,Rp 145.000.000,Rp 149.000.000 (Cash),"Rp 2,95 jt/bln",38.157 km Automatic Bandung
697,2014 Nissan MARCH ...,Rp 111.000.000,Rp 114.000.000 (Cash),"Rp 2,26 jt/bln",97.076 km Automatic Tangerang Selatan
698,2022 Daihatsu AYLA ...,Rp 131.000.000,Rp 135.000.000 (Cash),"Rp 2,67 jt/bln",3.226 km Automatic Jakarta Pusat
699,2016 Honda HR-V S ...,Rp 203.000.000,Rp 209.000.000 (Cash),"Rp 4,14 jt/bln",20.517 km Automatic Bekasi

In [14]:
pd.DataFrame(data).to_csv('Tugas Data Crawling_Gabriella Meisya T_096.csv')